services:
  - type: web
    name: my-laravel-app
    env: docker
    buildCommand: docker build -t my-laravel-app:latest .
    startCommand: docker run -p 80:80 my-laravel-app:latest
    plan: free
    regions:
      - oregon
