services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
     repo: https://github.com/Remedy1995/microcredit-api.git
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: ENV_VAR_NAME
        value: ENV_VAR_VALUE
