services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/Remedy1995/microcredit-api.git
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "service nginx start && php-fpm"
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
